import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        blueally: {
          navy: "#0339AF",
          royal: "#4C73E9",
          cyan: "#00B4D8",
          green: "#7A8B51",
          lightgreen: "#A3C585",
          orange: "#D97706",
          softblue: "#E0F2FE",
          dark: "#0a192f",
          light: "#f8faff",
          cream: "#FEFCF3",
          slate: "#1E293B",
          gray: "#64748B",
          border: "#E2E8F0",
        },
        "brand-navy": "#0339AF",
        "brand-blue": "#4C73E9",
        primary: {
          DEFAULT: "#0339AF",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#4C73E9",
          foreground: "#ffffff",
        },
        accent: {
          DEFAULT: "#7A8B51",
          foreground: "#ffffff",
        },
        background: "#f8faff",
        chart: {
          revenue: "#059669",
          cost: "#0339AF",
          cashflow: "#4C73E9",
          risk: "#D97706",
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'SF Mono',
          'Fira Code',
          'Consolas',
          'Monaco',
          'monospace',
        ],
        heading: ["Inter", "system-ui", "sans-serif"],
        display: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        'display-2xl': ['4.5rem', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['3.75rem', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-md': ['2.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'heading-xl': ['1.875rem', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-lg': ['1.5rem', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading': ['1.25rem', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-md': ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.7', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-sm': ['0.875rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-xs': ['0.8125rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label': ['0.875rem', { lineHeight: '1.4', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
        'caption': ['0.75rem', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.03em' }],
        'overline': ['0.6875rem', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.08em' }],
      },
      letterSpacing: {
        tightest: '-0.04em',
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0',
        wide: '0.02em',
        wider: '0.04em',
        widest: '0.08em',
      },
      lineHeight: {
        tightest: '1',
        tighter: '1.1',
        tight: '1.25',
        snug: '1.35',
        normal: '1.5',
        relaxed: '1.7',
        loose: '1.8',
      },
      borderRadius: {
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      boxShadow: {
        "card": "0 1px 3px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)",
        "card-hover": "0 10px 25px rgba(0, 0, 0, 0.08), 0 4px 10px rgba(0, 0, 0, 0.04)",
        "stat": "0 4px 14px rgba(3, 57, 175, 0.12)",
        "glow": "0 0 20px rgba(76, 115, 233, 0.25)",
      },
      backgroundImage: {
        "gradient-navy": "linear-gradient(135deg, #0339AF 0%, #4C73E9 100%)",
        "gradient-success": "linear-gradient(135deg, #7A8B51 0%, #A3C585 100%)",
        "gradient-light": "linear-gradient(180deg, #ffffff 0%, #f8faff 100%)",
        "gradient-dark": "linear-gradient(135deg, #0a192f 0%, #1a365d 100%)",
        "gradient-stat": "linear-gradient(135deg, #f8faff 0%, #E0F2FE 100%)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
        "count-up": "countUp 2s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        countUp: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};

export default config;
