import type { WorkflowStep, TargetWorkflowStep, WorkflowComparisonMetrics, AgenticPattern } from "@shared/schema";

export interface UseCaseWorkflowTemplate {
  keywords: string[];
  businessFunction: string;
  agenticPattern: AgenticPattern;
  patternRationale: string;
  currentStateWorkflow: WorkflowStep[];
  targetStateWorkflow: Omit<TargetWorkflowStep, "agentType">[];
  comparisonMetrics: WorkflowComparisonMetrics;
  implementationNotes: string[];
  humanCheckpoints: string[];
}

export const USE_CASE_TEMPLATES: UseCaseWorkflowTemplate[] = [
  {
    keywords: ["lead", "scoring", "routing", "qualification", "prospect", "sales rep"],
    businessFunction: "Sales & Distribution",
    agenticPattern: "Semantic Router",
    patternRationale: "Semantic Router pattern excels at intelligent lead classification and routing, using 47+ variables to score and match leads to the most suitable representatives. It reduces manual triage time by 70-90% while improving conversion rates.",
    currentStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "CS-01",
        stepName: "Lead Arrives in CRM",
        description: "Leads from campaigns, web forms, and referrals arrive in CRM system without enrichment or scoring",
        actor: { type: "system", name: "CRM System", role: "Data Capture" },
        duration: { value: 0, unit: "seconds", variability: "per item" },
        systems: ["CRM", "Web Forms"],
        dataSources: ["Campaign responses", "Website forms"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["No lead enrichment", "Basic data only"],
        connectedTo: ["CS-02"],
      },
      {
        stepNumber: 2,
        stepId: "CS-02",
        stepName: "Round-Robin Assignment",
        description: "Leads distributed to reps via round-robin with no intelligence about rep specialty or lead characteristics",
        actor: { type: "system", name: "Assignment Engine", role: "Distribution" },
        duration: { value: 1, unit: "minutes", variability: "per batch" },
        systems: ["CRM"],
        dataSources: ["Rep roster"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["No skill matching", "Ignores rep expertise", "Poor lead-rep fit"],
        connectedTo: ["CS-03"],
      },
      {
        stepNumber: 3,
        stepId: "CS-03",
        stepName: "Manual Lead Review",
        description: "Rep manually reviews lead profile, researches company, and assesses potential value",
        actor: { type: "human", name: "Sales Representative", role: "Sales" },
        duration: { value: 8, unit: "minutes", variability: "per item" },
        systems: ["CRM", "LinkedIn", "Company Website"],
        dataSources: ["Lead profile", "Public data"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["58% of time on low-probability prospects", "Manual research time", "Inconsistent evaluation"],
        connectedTo: ["CS-04"],
      },
      {
        stepNumber: 4,
        stepId: "CS-04",
        stepName: "Gut-Feel Prioritization",
        description: "Rep prioritizes leads based on intuition and assigns Low/Medium/High labels",
        actor: { type: "human", name: "Sales Representative", role: "Sales" },
        duration: { value: 3, unit: "minutes", variability: "per item" },
        systems: ["CRM"],
        dataSources: ["Personal experience"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: true,
        painPoints: ["Subjective scoring", "Inconsistent across reps", "No data-driven insights"],
        connectedTo: ["CS-05"],
      },
      {
        stepNumber: 5,
        stepId: "CS-05",
        stepName: "Manual Outreach Attempts",
        description: "Rep crafts personalized outreach without context or AI assistance",
        actor: { type: "human", name: "Sales Representative", role: "Sales" },
        duration: { value: 12, unit: "minutes", variability: "per item" },
        systems: ["Email", "Phone"],
        dataSources: ["Lead data", "Templates"],
        isBottleneck: true,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Time-consuming personalization", "Generic messaging", "Low response rates"],
        connectedTo: ["CS-06"],
      },
      {
        stepNumber: 6,
        stepId: "CS-06",
        stepName: "Outcome Logging",
        description: "Rep manually logs call/email outcomes in CRM with inconsistent detail",
        actor: { type: "human", name: "Sales Representative", role: "Sales" },
        duration: { value: 5, unit: "minutes", variability: "per item" },
        systems: ["CRM"],
        dataSources: ["Call notes"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Inconsistent data entry", "Delayed updates", "Missing context"],
        connectedTo: ["CS-07"],
      },
      {
        stepNumber: 7,
        stepId: "CS-07",
        stepName: "Monthly Conversion Report",
        description: "Manager generates backward-looking report on lead conversion rates",
        actor: { type: "human", name: "Sales Manager", role: "Management" },
        duration: { value: 4, unit: "hours", variability: "per batch" },
        systems: ["CRM", "Excel"],
        dataSources: ["Historical data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Backward-looking only", "No predictive insights", "Manual compilation"],
        connectedTo: [],
      },
    ],
    targetStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "TS-01",
        stepName: "Multi-Channel Lead Ingestion & Enrichment",
        description: "AI automatically captures leads from all channels, enriches with 47+ data points from firmographic and intent sources",
        actor: { type: "ai_agent", name: "Lead Enrichment Agent", role: "Data Processing" },
        duration: { value: 5, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Data Enrichment APIs", "CRM"],
        dataSources: ["Firmographic databases", "Intent signals", "Social data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-02"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Data Extraction", "Enrichment", "Validation"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 2,
        stepId: "TS-02",
        stepName: "AI Lead Scoring (0-100)",
        description: "AI scores lead using 47 variables including firmographics, behavior, intent, and fit criteria",
        actor: { type: "ai_agent", name: "Lead Scoring Agent", role: "Predictive Analytics" },
        duration: { value: 2, unit: "seconds", variability: "per item" },
        systems: ["ML Platform", "CRM"],
        dataSources: ["Historical conversion data", "Behavioral signals"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-03"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Prediction", "Classification", "Scoring"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 3,
        stepId: "TS-03",
        stepName: "Intelligent Rep-Lead Matching",
        description: "AI matches leads to reps based on specialty, performance history, and workload",
        actor: { type: "ai_agent", name: "Routing Agent", role: "Assignment Optimization" },
        duration: { value: 1, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "CRM"],
        dataSources: ["Rep profiles", "Performance data", "Workload"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-04"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Routing", "Optimization", "Matching"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 4,
        stepId: "TS-04",
        stepName: "AI Generates Personalized Brief",
        description: "AI creates customized lead brief with talking points, potential objections, and recommended approach",
        actor: { type: "ai_agent", name: "Brief Generator", role: "Content Creation" },
        duration: { value: 8, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Knowledge Base"],
        dataSources: ["Company research", "Industry insights", "Similar deals"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-05"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Generation", "Personalization", "Research"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 5,
        stepId: "TS-05",
        stepName: "Rep Reviews AI Recommendations",
        description: "Sales rep reviews AI scoring, brief, and recommendations before outreach",
        actor: { type: "human", name: "Sales Representative", role: "Sales" },
        duration: { value: 2, unit: "minutes", variability: "per item" },
        systems: ["Sales Dashboard"],
        dataSources: ["AI recommendations", "Lead brief"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-06"],
        isAIEnabled: false,
        isHumanInTheLoop: true,
        aiCapabilities: [],
        model: null,
        automationLevel: "supervised",
      },
      {
        stepNumber: 6,
        stepId: "TS-06",
        stepName: "Contextual Outreach Execution",
        description: "Rep conducts personalized outreach using AI-generated insights and talking points",
        actor: { type: "human", name: "Sales Representative", role: "Sales" },
        duration: { value: 8, unit: "minutes", variability: "per item" },
        systems: ["Email", "Phone", "CRM"],
        dataSources: ["AI brief", "Lead data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-07"],
        isAIEnabled: false,
        isHumanInTheLoop: false,
        aiCapabilities: [],
        model: null,
        automationLevel: "manual",
      },
      {
        stepNumber: 7,
        stepId: "TS-07",
        stepName: "AI Captures Outcome & Triggers Next Action",
        description: "AI automatically logs outcomes, updates lead status, and triggers appropriate follow-up actions",
        actor: { type: "ai_agent", name: "Outcome Processor", role: "Workflow Automation" },
        duration: { value: 3, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "CRM", "Marketing Automation"],
        dataSources: ["Call/email content", "CRM data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-08"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Classification", "Workflow Automation", "Decision"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 8,
        stepId: "TS-08",
        stepName: "Feedback Loop Updates Scoring Model",
        description: "Conversion outcomes feed back to improve lead scoring accuracy over time",
        actor: { type: "system", name: "ML Pipeline", role: "Continuous Learning" },
        duration: { value: 0, unit: "seconds", variability: "fixed" },
        systems: ["ML Platform"],
        dataSources: ["Conversion data", "Outcome history"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: [],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Learning", "Model Refinement"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
    ],
    comparisonMetrics: {
      timeReduction: { before: "28 min/lead", after: "10 min/lead", improvement: "64%" },
      costReduction: { before: "$45/lead", after: "$16/lead", improvement: "64%" },
      qualityImprovement: { before: "12% conversion", after: "28% conversion", improvement: "133%" },
      throughputIncrease: { before: "15 leads/day", after: "45 leads/day", improvement: "200%" },
    },
    implementationNotes: [
      "Start with high-volume lead sources for maximum impact",
      "Calibrate scoring model with 90 days of historical conversion data",
      "Phase in rep matching after scoring model proves accurate",
    ],
    humanCheckpoints: [
      "Step TS-05: Rep reviews all AI recommendations before outreach",
      "High-value leads (>$100K potential) require manager approval",
    ],
  },
  {
    keywords: ["underwriting", "document", "medical", "extraction", "ocr", "risk assessment"],
    businessFunction: "Underwriting & Risk",
    agenticPattern: "Drafter-Critic",
    patternRationale: "Drafter-Critic pattern excels at document intelligence, with one agent extracting data while another validates accuracy. This dual-agent approach ensures high-quality extraction from complex medical and financial documents.",
    currentStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "CS-01",
        stepName: "Document Receipt",
        description: "Application documents arrive via mail, fax, and email in various formats",
        actor: { type: "human", name: "Document Clerk", role: "Operations" },
        duration: { value: 15, unit: "minutes", variability: "per item" },
        systems: ["Email", "Fax", "Mail Room"],
        dataSources: ["Incoming mail", "Email attachments"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Multiple input channels", "Inconsistent formats", "Manual logging"],
        connectedTo: ["CS-02"],
      },
      {
        stepNumber: 2,
        stepId: "CS-02",
        stepName: "Manual Document Sorting",
        description: "Clerk manually sorts documents by type (medical records, financials, applications)",
        actor: { type: "human", name: "Document Clerk", role: "Operations" },
        duration: { value: 20, unit: "minutes", variability: "per item" },
        systems: ["Document Management"],
        dataSources: ["Physical/digital documents"],
        isBottleneck: true,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Time-consuming sorting", "Misclassification errors", "Bottleneck at intake"],
        connectedTo: ["CS-03"],
      },
      {
        stepNumber: 3,
        stepId: "CS-03",
        stepName: "Data Entry from Forms",
        description: "Staff manually enters data from application forms into underwriting system",
        actor: { type: "human", name: "Data Entry Specialist", role: "Operations" },
        duration: { value: 30, unit: "minutes", variability: "per item" },
        systems: ["Underwriting System", "Spreadsheet"],
        dataSources: ["Application forms"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Manual keying errors", "Slow processing", "Data inconsistencies"],
        connectedTo: ["CS-04"],
      },
      {
        stepNumber: 4,
        stepId: "CS-04",
        stepName: "Medical Records Review",
        description: "Underwriter manually reviews medical records to extract key health information",
        actor: { type: "human", name: "Underwriter", role: "Underwriting" },
        duration: { value: 4, unit: "hours", variability: "per item" },
        systems: ["Medical Records Viewer"],
        dataSources: ["Medical records", "Lab results"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["65% of time on data extraction", "Complex medical terminology", "High cognitive load"],
        connectedTo: ["CS-05"],
      },
      {
        stepNumber: 5,
        stepId: "CS-05",
        stepName: "Financial Document Analysis",
        description: "Underwriter analyzes financial statements and tax returns",
        actor: { type: "human", name: "Underwriter", role: "Underwriting" },
        duration: { value: 45, unit: "minutes", variability: "per item" },
        systems: ["Financial Analysis Tools"],
        dataSources: ["Financial statements", "Tax returns"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Manual calculations", "Cross-document validation"],
        connectedTo: ["CS-06"],
      },
      {
        stepNumber: 6,
        stepId: "CS-06",
        stepName: "Risk Score Calculation",
        description: "Underwriter uses lookup tables and guidelines to calculate risk score",
        actor: { type: "human", name: "Underwriter", role: "Underwriting" },
        duration: { value: 30, unit: "minutes", variability: "per item" },
        systems: ["Rate Manual", "Excel"],
        dataSources: ["Extracted data", "Risk tables"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: true,
        painPoints: ["Manual lookup errors", "Outdated guidelines", "Inconsistent application"],
        connectedTo: ["CS-07"],
      },
      {
        stepNumber: 7,
        stepId: "CS-07",
        stepName: "Decision Documentation",
        description: "Underwriter documents decision rationale and prepares case file",
        actor: { type: "human", name: "Underwriter", role: "Underwriting" },
        duration: { value: 25, unit: "minutes", variability: "per item" },
        systems: ["Case Management"],
        dataSources: ["Analysis notes"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Documentation burden", "Inconsistent detail"],
        connectedTo: ["CS-08"],
      },
      {
        stepNumber: 8,
        stepId: "CS-08",
        stepName: "Quality Review",
        description: "Senior underwriter reviews decision before policy issuance",
        actor: { type: "human", name: "Senior Underwriter", role: "Quality" },
        duration: { value: 20, unit: "minutes", variability: "per item" },
        systems: ["Case Management"],
        dataSources: ["Case file"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: ["Review backlog", "Rework cycles"],
        connectedTo: [],
      },
    ],
    targetStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "TS-01",
        stepName: "Intelligent Document Capture",
        description: "AI-powered OCR captures documents from all channels and digitizes content",
        actor: { type: "ai_agent", name: "OCR Agent", role: "Document Capture" },
        duration: { value: 30, unit: "seconds", variability: "per item" },
        systems: ["AI OCR Platform", "Document Management"],
        dataSources: ["Email", "Fax", "Portal uploads"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-02"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["OCR", "Image Processing", "Text Extraction"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 2,
        stepId: "TS-02",
        stepName: "AI Document Classification",
        description: "AI classifies documents by type and routes to appropriate extraction pipeline",
        actor: { type: "ai_agent", name: "Classification Agent", role: "Document Routing" },
        duration: { value: 5, unit: "seconds", variability: "per item" },
        systems: ["AI Platform"],
        dataSources: ["Document content"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-03"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Classification", "Routing"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 3,
        stepId: "TS-03",
        stepName: "Automated Data Extraction (NLP)",
        description: "NLP models extract structured data from forms, tables, and narrative text",
        actor: { type: "ai_agent", name: "Extraction Agent", role: "Data Processing" },
        duration: { value: 45, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Underwriting System"],
        dataSources: ["Classified documents"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-04"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["NLP", "Entity Extraction", "Table Parsing"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 4,
        stepId: "TS-04",
        stepName: "AI Medical History Synthesis",
        description: "AI synthesizes medical records into structured health summary with key risk factors",
        actor: { type: "ai_agent", name: "Medical Analysis Agent", role: "Medical Intelligence" },
        duration: { value: 2, unit: "minutes", variability: "per item" },
        systems: ["AI Platform", "Medical Terminology DB"],
        dataSources: ["Medical records", "Lab results"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-05"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Medical NLP", "Summarization", "Risk Detection"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 5,
        stepId: "TS-05",
        stepName: "Risk Factor Identification",
        description: "AI identifies and scores risk factors from medical and financial data",
        actor: { type: "ai_agent", name: "Risk Detection Agent", role: "Risk Analysis" },
        duration: { value: 30, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Risk Engine"],
        dataSources: ["Extracted data", "Risk guidelines"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-06"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Risk Assessment", "Pattern Recognition"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 6,
        stepId: "TS-06",
        stepName: "AI Risk Summary Generation",
        description: "AI generates comprehensive risk summary with recommendation and confidence score",
        actor: { type: "ai_agent", name: "Summary Agent", role: "Decision Support" },
        duration: { value: 20, unit: "seconds", variability: "per item" },
        systems: ["AI Platform"],
        dataSources: ["Risk factors", "Guidelines"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-07"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Generation", "Summarization"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 7,
        stepId: "TS-07",
        stepName: "Underwriter Validates AI Recommendation",
        description: "Underwriter reviews AI summary and recommendation, approves or modifies decision",
        actor: { type: "human", name: "Underwriter", role: "Underwriting" },
        duration: { value: 15, unit: "minutes", variability: "per item" },
        systems: ["Underwriting Dashboard"],
        dataSources: ["AI summary", "Source documents"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-08"],
        isAIEnabled: false,
        isHumanInTheLoop: true,
        aiCapabilities: [],
        model: null,
        automationLevel: "supervised",
      },
      {
        stepNumber: 8,
        stepId: "TS-08",
        stepName: "Automated Decision Documentation",
        description: "AI generates complete decision documentation and audit trail",
        actor: { type: "ai_agent", name: "Documentation Agent", role: "Compliance" },
        duration: { value: 10, unit: "seconds", variability: "per item" },
        systems: ["Case Management", "Audit System"],
        dataSources: ["Decision data", "Underwriter notes"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: [],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Generation", "Compliance"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
    ],
    comparisonMetrics: {
      timeReduction: { before: "6.5 hrs/case", after: "20 min/case", improvement: "95%" },
      costReduction: { before: "$350/case", after: "$45/case", improvement: "87%" },
      qualityImprovement: { before: "89% accuracy", after: "98% accuracy", improvement: "10%" },
      throughputIncrease: { before: "8 cases/day", after: "48 cases/day", improvement: "500%" },
    },
    implementationNotes: [
      "Pilot with standardized forms before complex medical records",
      "Build confidence scores to determine routing to human review",
      "Continuous model training with underwriter feedback",
    ],
    humanCheckpoints: [
      "Step TS-07: Underwriter validates all AI recommendations",
      "Cases with confidence < 85% require full manual review",
    ],
  },
  {
    keywords: ["compliance", "surveillance", "alert", "triage", "false positive", "regulatory"],
    businessFunction: "Compliance & Risk Management",
    agenticPattern: "Constitutional Guardrail",
    patternRationale: "Constitutional Guardrail pattern ensures compliance decisions align with regulatory requirements. It validates all outputs against policy rules, reducing false positives while maintaining audit trails.",
    currentStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "CS-01",
        stepName: "Rules Engine Alert Generation",
        description: "Legacy rules engine generates 340 alerts/day based on static thresholds",
        actor: { type: "system", name: "Rules Engine", role: "Monitoring" },
        duration: { value: 0, unit: "seconds", variability: "per batch" },
        systems: ["Surveillance System"],
        dataSources: ["Transaction data"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["82% false positive rate", "Static rules miss patterns", "Alert fatigue"],
        connectedTo: ["CS-02"],
      },
      {
        stepNumber: 2,
        stepId: "CS-02",
        stepName: "Alerts Queue Management",
        description: "Alerts accumulate in compliance queue awaiting investigation",
        actor: { type: "system", name: "Case Management", role: "Queue" },
        duration: { value: 24, unit: "hours", variability: "per item" },
        systems: ["Compliance System"],
        dataSources: ["Alert queue"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Growing backlog", "SLA breaches", "Priority confusion"],
        connectedTo: ["CS-03"],
      },
      {
        stepNumber: 3,
        stepId: "CS-03",
        stepName: "Analyst Opens Alert",
        description: "Compliance analyst picks up alert from queue for investigation",
        actor: { type: "human", name: "Compliance Analyst", role: "Compliance" },
        duration: { value: 5, unit: "minutes", variability: "per item" },
        systems: ["Compliance System"],
        dataSources: ["Alert details"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Limited context", "Manual case setup"],
        connectedTo: ["CS-04"],
      },
      {
        stepNumber: 4,
        stepId: "CS-04",
        stepName: "Manual Transaction Lookup",
        description: "Analyst manually searches multiple systems to gather transaction context",
        actor: { type: "human", name: "Compliance Analyst", role: "Compliance" },
        duration: { value: 25, unit: "minutes", variability: "per item" },
        systems: ["Core Banking", "Trading System", "CRM"],
        dataSources: ["Transaction history", "Customer data"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["4,800 hrs/month on investigation", "Multiple system lookups", "Time-consuming research"],
        connectedTo: ["CS-05"],
      },
      {
        stepNumber: 5,
        stepId: "CS-05",
        stepName: "Communication Review",
        description: "Analyst reviews customer and rep communications for suspicious patterns",
        actor: { type: "human", name: "Compliance Analyst", role: "Compliance" },
        duration: { value: 20, unit: "minutes", variability: "per item" },
        systems: ["Email Archive", "Call Recording"],
        dataSources: ["Communications"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Volume of communications", "Manual text review"],
        connectedTo: ["CS-06"],
      },
      {
        stepNumber: 6,
        stepId: "CS-06",
        stepName: "False Positive Documentation",
        description: "Analyst documents why alert is false positive (82% of cases)",
        actor: { type: "human", name: "Compliance Analyst", role: "Compliance" },
        duration: { value: 15, unit: "minutes", variability: "per item" },
        systems: ["Compliance System"],
        dataSources: ["Investigation notes"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: true,
        painPoints: ["Documentation burden", "Repetitive work", "Low-value activity"],
        connectedTo: ["CS-07"],
      },
      {
        stepNumber: 7,
        stepId: "CS-07",
        stepName: "Case Escalation or Closure",
        description: "Analyst escalates suspicious cases or closes false positives",
        actor: { type: "human", name: "Compliance Analyst", role: "Compliance" },
        duration: { value: 10, unit: "minutes", variability: "per item" },
        systems: ["Case Management"],
        dataSources: ["Case file"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: ["Manual routing", "Inconsistent escalation criteria"],
        connectedTo: ["CS-08"],
      },
      {
        stepNumber: 8,
        stepId: "CS-08",
        stepName: "Monthly Regulatory Reporting",
        description: "Compliance team compiles monthly regulatory reports manually",
        actor: { type: "human", name: "Compliance Manager", role: "Reporting" },
        duration: { value: 16, unit: "hours", variability: "per batch" },
        systems: ["Excel", "Regulatory Portal"],
        dataSources: ["Case data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Manual compilation", "Error-prone aggregation"],
        connectedTo: [],
      },
    ],
    targetStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "TS-01",
        stepName: "ML Behavioral Analysis",
        description: "ML models analyze transactions in real-time using behavioral patterns vs. static rules",
        actor: { type: "ai_agent", name: "Behavioral ML Agent", role: "Risk Detection" },
        duration: { value: 100, unit: "seconds", variability: "per batch" },
        systems: ["ML Platform", "Transaction System"],
        dataSources: ["Transaction streams", "Historical patterns"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-02"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Anomaly Detection", "Pattern Recognition", "Behavioral Analysis"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 2,
        stepId: "TS-02",
        stepName: "Contextual Risk Scoring",
        description: "AI scores risk considering customer history, peer behavior, and market context",
        actor: { type: "ai_agent", name: "Risk Scoring Agent", role: "Risk Assessment" },
        duration: { value: 5, unit: "seconds", variability: "per item" },
        systems: ["AI Platform"],
        dataSources: ["Customer profiles", "Peer data", "Market signals"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-03"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Risk Scoring", "Contextual Analysis"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 3,
        stepId: "TS-03",
        stepName: "AI Alert Triage (High/Med/Low)",
        description: "AI triages alerts into priority tiers based on risk severity and confidence",
        actor: { type: "ai_agent", name: "Triage Agent", role: "Alert Management" },
        duration: { value: 2, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Case Management"],
        dataSources: ["Risk scores", "Alert metadata"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-04"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Classification", "Priority Routing"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 4,
        stepId: "TS-04",
        stepName: "Auto-Generated Evidence Package",
        description: "AI assembles complete evidence package with transactions, communications, and context",
        actor: { type: "ai_agent", name: "Evidence Assembly Agent", role: "Investigation Support" },
        duration: { value: 30, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Data Aggregation"],
        dataSources: ["All source systems"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-05"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Data Aggregation", "Summarization", "Evidence Assembly"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 5,
        stepId: "TS-05",
        stepName: "Analyst Reviews High-Risk Cases",
        description: "Compliance analyst reviews AI-prepared evidence for high-risk alerts only",
        actor: { type: "human", name: "Compliance Analyst", role: "Compliance" },
        duration: { value: 10, unit: "minutes", variability: "per item" },
        systems: ["Investigation Dashboard"],
        dataSources: ["AI evidence package", "Source documents"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-06"],
        isAIEnabled: false,
        isHumanInTheLoop: true,
        aiCapabilities: [],
        model: null,
        automationLevel: "supervised",
      },
      {
        stepNumber: 6,
        stepId: "TS-06",
        stepName: "AI Handles Low-Risk with Audit Trail",
        description: "AI automatically closes low-risk alerts with complete documentation and audit trail",
        actor: { type: "ai_agent", name: "Auto-Resolution Agent", role: "Case Management" },
        duration: { value: 5, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Audit System"],
        dataSources: ["Case data", "Resolution templates"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-07"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Decision", "Documentation", "Audit"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 7,
        stepId: "TS-07",
        stepName: "Pattern Learning from Outcomes",
        description: "ML models learn from analyst decisions to improve future detection",
        actor: { type: "system", name: "Learning Pipeline", role: "Continuous Improvement" },
        duration: { value: 0, unit: "seconds", variability: "fixed" },
        systems: ["ML Platform"],
        dataSources: ["Resolution outcomes", "Analyst feedback"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-08"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Learning", "Model Refinement"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 8,
        stepId: "TS-08",
        stepName: "Automated Regulatory Reporting",
        description: "AI generates regulatory reports automatically with complete audit trails",
        actor: { type: "ai_agent", name: "Reporting Agent", role: "Regulatory Compliance" },
        duration: { value: 5, unit: "minutes", variability: "per item" },
        systems: ["Reporting Platform", "Regulatory Portal"],
        dataSources: ["Case outcomes", "Metrics"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: [],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Report Generation", "Aggregation"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
    ],
    comparisonMetrics: {
      timeReduction: { before: "75 min/alert", after: "12 min/alert", improvement: "84%" },
      costReduction: { before: "$125/alert", after: "$22/alert", improvement: "82%" },
      qualityImprovement: { before: "18% true positive", after: "72% true positive", improvement: "300%" },
      throughputIncrease: { before: "45 alerts/day", after: "280 alerts/day", improvement: "522%" },
    },
    implementationNotes: [
      "Start with low-risk alert auto-resolution to demonstrate value",
      "Maintain 100% audit trail for regulatory examination readiness",
      "Gradual threshold adjustment as model accuracy improves",
    ],
    humanCheckpoints: [
      "Step TS-05: Analyst reviews all high-risk cases",
      "Any SAR-eligible cases require human escalation",
    ],
  },
  {
    keywords: ["onboarding", "training", "certification", "rep", "learning", "coaching"],
    businessFunction: "Sales & Distribution",
    agenticPattern: "Memetic Agent",
    patternRationale: "Memetic Agent pattern excels at personalized learning experiences, adapting content and pacing to individual rep backgrounds, learning styles, and progress. It creates tailored onboarding paths that accelerate time-to-productivity.",
    currentStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "CS-01",
        stepName: "New Rep Application",
        description: "New representative submits application and required documentation",
        actor: { type: "human", name: "Recruiting Team", role: "HR" },
        duration: { value: 2, unit: "days", variability: "per item" },
        systems: ["ATS", "Email"],
        dataSources: ["Application", "Resume"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Manual document collection", "Inconsistent intake"],
        connectedTo: ["CS-02"],
      },
      {
        stepNumber: 2,
        stepId: "CS-02",
        stepName: "Background Check Processing",
        description: "Background check and licensing verification processed",
        actor: { type: "human", name: "Compliance Team", role: "Compliance" },
        duration: { value: 7, unit: "days", variability: "per item" },
        systems: ["Background Check System"],
        dataSources: ["External databases"],
        isBottleneck: true,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: ["Long wait times", "Manual follow-ups"],
        connectedTo: ["CS-03"],
      },
      {
        stepNumber: 3,
        stepId: "CS-03",
        stepName: "Licensing Exam Scheduling",
        description: "Rep scheduled for required licensing exams",
        actor: { type: "human", name: "Training Coordinator", role: "Training" },
        duration: { value: 3, unit: "days", variability: "per item" },
        systems: ["LMS", "Calendar"],
        dataSources: ["Exam schedules"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Limited exam slots", "Scheduling conflicts"],
        connectedTo: ["CS-04"],
      },
      {
        stepNumber: 4,
        stepId: "CS-04",
        stepName: "Generic Training Assignment",
        description: "One-size-fits-all training curriculum assigned regardless of experience",
        actor: { type: "human", name: "Training Coordinator", role: "Training" },
        duration: { value: 1, unit: "hours", variability: "per item" },
        systems: ["LMS"],
        dataSources: ["Training catalog"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["No personalization", "Experienced reps waste time", "90-day time-to-productivity"],
        connectedTo: ["CS-05"],
      },
      {
        stepNumber: 5,
        stepId: "CS-05",
        stepName: "Classroom/Video Training",
        description: "Rep completes 40 hours of standardized training content",
        actor: { type: "human", name: "New Representative", role: "Sales" },
        duration: { value: 40, unit: "hours", variability: "fixed" },
        systems: ["LMS", "Classroom"],
        dataSources: ["Training materials"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["One-size-fits-all", "No adaptive pacing", "Low engagement"],
        connectedTo: ["CS-06"],
      },
      {
        stepNumber: 6,
        stepId: "CS-06",
        stepName: "Product Certification Exams",
        description: "Rep takes certification exams for each product line",
        actor: { type: "human", name: "New Representative", role: "Sales" },
        duration: { value: 8, unit: "hours", variability: "per item" },
        systems: ["LMS"],
        dataSources: ["Exam results"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: ["Pass/fail only", "No targeted remediation"],
        connectedTo: ["CS-07"],
      },
      {
        stepNumber: 7,
        stepId: "CS-07",
        stepName: "First Field Assignment",
        description: "Rep begins selling with limited support",
        actor: { type: "human", name: "New Representative", role: "Sales" },
        duration: { value: 30, unit: "days", variability: "fixed" },
        systems: ["CRM"],
        dataSources: ["Sales tools"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Sink or swim", "Limited real-time support", "High early attrition"],
        connectedTo: ["CS-08"],
      },
      {
        stepNumber: 8,
        stepId: "CS-08",
        stepName: "Monthly Performance Review",
        description: "Manager reviews rep performance monthly",
        actor: { type: "human", name: "Sales Manager", role: "Management" },
        duration: { value: 1, unit: "hours", variability: "per batch" },
        systems: ["CRM", "Excel"],
        dataSources: ["Sales data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: ["Lagging indicators", "Reactive coaching"],
        connectedTo: [],
      },
    ],
    targetStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "TS-01",
        stepName: "AI Background Assessment",
        description: "AI analyzes rep background, experience, and existing certifications",
        actor: { type: "ai_agent", name: "Assessment Agent", role: "Evaluation" },
        duration: { value: 5, unit: "minutes", variability: "per item" },
        systems: ["AI Platform", "ATS"],
        dataSources: ["Resume", "Credentials", "Prior experience"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-02"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Analysis", "Pattern Recognition", "Skill Assessment"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 2,
        stepId: "TS-02",
        stepName: "Personalized Curriculum Generation",
        description: "AI creates customized learning path based on skill gaps and learning style",
        actor: { type: "ai_agent", name: "Curriculum Agent", role: "Learning Design" },
        duration: { value: 2, unit: "minutes", variability: "per item" },
        systems: ["AI Platform", "LMS"],
        dataSources: ["Assessment results", "Training library"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-03"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Personalization", "Curriculum Design", "Gap Analysis"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 3,
        stepId: "TS-03",
        stepName: "Adaptive Microlearning Delivery",
        description: "AI delivers bite-sized learning content adapted to rep's pace and retention",
        actor: { type: "ai_agent", name: "Learning Agent", role: "Content Delivery" },
        duration: { value: 15, unit: "hours", variability: "per item" },
        systems: ["AI Platform", "Mobile App"],
        dataSources: ["Learning progress", "Performance data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-04"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Adaptive Learning", "Content Personalization", "Progress Tracking"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 4,
        stepId: "TS-04",
        stepName: "AI Coaching Chatbot (24/7)",
        description: "AI chatbot provides instant answers to product, process, and sales questions",
        actor: { type: "ai_agent", name: "Coaching Bot", role: "Real-time Support" },
        duration: { value: 30, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Knowledge Base"],
        dataSources: ["Product info", "Sales playbooks", "Policies"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-05"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Q&A", "Knowledge Retrieval", "Coaching"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 5,
        stepId: "TS-05",
        stepName: "AI Knowledge Gap Detection",
        description: "AI identifies specific knowledge gaps from interactions and quiz performance",
        actor: { type: "ai_agent", name: "Gap Analysis Agent", role: "Assessment" },
        duration: { value: 0, unit: "seconds", variability: "fixed" },
        systems: ["AI Platform", "LMS"],
        dataSources: ["Interaction logs", "Quiz results"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-06"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Analysis", "Gap Detection", "Remediation Planning"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 6,
        stepId: "TS-06",
        stepName: "Human Mentor Session Triggers",
        description: "AI schedules human mentor sessions when rep needs personalized guidance",
        actor: { type: "human", name: "Mentor", role: "Coaching" },
        duration: { value: 30, unit: "minutes", variability: "per item" },
        systems: ["Calendar", "Video Conferencing"],
        dataSources: ["AI recommendations"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-07"],
        isAIEnabled: false,
        isHumanInTheLoop: true,
        aiCapabilities: [],
        model: null,
        automationLevel: "supervised",
      },
      {
        stepNumber: 7,
        stepId: "TS-07",
        stepName: "Accelerated Certification Path",
        description: "AI-optimized certification timeline based on demonstrated competency",
        actor: { type: "ai_agent", name: "Certification Agent", role: "Credentialing" },
        duration: { value: 20, unit: "hours", variability: "per item" },
        systems: ["LMS", "AI Platform"],
        dataSources: ["Competency data", "Exam results"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-08"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Assessment", "Certification Management"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 8,
        stepId: "TS-08",
        stepName: "Continuous Skill Development",
        description: "AI provides ongoing learning recommendations based on performance and market changes",
        actor: { type: "ai_agent", name: "Development Agent", role: "Continuous Learning" },
        duration: { value: 0, unit: "seconds", variability: "fixed" },
        systems: ["AI Platform", "LMS"],
        dataSources: ["Performance data", "Market trends"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: [],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Recommendation", "Learning Path Optimization"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
    ],
    comparisonMetrics: {
      timeReduction: { before: "90 days productivity", after: "45 days productivity", improvement: "50%" },
      costReduction: { before: "$25K/rep", after: "$12K/rep", improvement: "52%" },
      qualityImprovement: { before: "62% 1yr retention", after: "84% 1yr retention", improvement: "35%" },
      throughputIncrease: { before: "15 reps/month", after: "35 reps/month", improvement: "133%" },
    },
    implementationNotes: [
      "Integrate with existing LMS for seamless content delivery",
      "Build coaching bot knowledge base from top performer techniques",
      "Measure time-to-first-sale as primary success metric",
    ],
    humanCheckpoints: [
      "Step TS-06: Human mentors validate AI-identified skill gaps",
      "Final certification requires human proctor for compliance",
    ],
  },
  {
    keywords: ["cross-sell", "recommendation", "next-best-action", "product", "household", "client services"],
    businessFunction: "Client Services",
    agenticPattern: "Memetic Agent",
    patternRationale: "Memetic Agent pattern learns from each client interaction to personalize product recommendations. It builds individual preference profiles and timing models to optimize cross-sell success rates.",
    currentStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "CS-01",
        stepName: "Client Contacts Rep",
        description: "Client reaches out to rep for service request or inquiry",
        actor: { type: "human", name: "Client", role: "Customer" },
        duration: { value: 0, unit: "minutes", variability: "per item" },
        systems: ["Phone", "Email"],
        dataSources: ["Inbound contact"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: ["Reactive engagement only", "No proactive outreach"],
        connectedTo: ["CS-02"],
      },
      {
        stepNumber: 2,
        stepId: "CS-02",
        stepName: "Basic Account Review",
        description: "Rep checks basic account information and current products",
        actor: { type: "human", name: "Service Representative", role: "Client Services" },
        duration: { value: 5, unit: "minutes", variability: "per item" },
        systems: ["CRM"],
        dataSources: ["Account data"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["1.4 products/household vs 2.1 target", "Limited client view"],
        connectedTo: ["CS-03"],
      },
      {
        stepNumber: 3,
        stepId: "CS-03",
        stepName: "Manual Needs Assessment",
        description: "Rep manually assesses additional needs if time permits",
        actor: { type: "human", name: "Service Representative", role: "Client Services" },
        duration: { value: 10, unit: "minutes", variability: "per item" },
        systems: ["CRM", "Notes"],
        dataSources: ["Conversation"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: true,
        painPoints: ["Inconsistent execution", "Time pressure", "No data-driven insights"],
        connectedTo: ["CS-04"],
      },
      {
        stepNumber: 4,
        stepId: "CS-04",
        stepName: "Generic Product Sharing",
        description: "Rep shares generic product brochures if opportunity identified",
        actor: { type: "human", name: "Service Representative", role: "Client Services" },
        duration: { value: 5, unit: "minutes", variability: "per item" },
        systems: ["Document Library"],
        dataSources: ["Marketing materials"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["One-size-fits-all materials", "Low engagement", "No personalization"],
        connectedTo: ["CS-05"],
      },
      {
        stepNumber: 5,
        stepId: "CS-05",
        stepName: "Annual Review Scheduling",
        description: "Rep schedules annual review meeting (only formal touchpoint)",
        actor: { type: "human", name: "Service Representative", role: "Client Services" },
        duration: { value: 3, unit: "minutes", variability: "per item" },
        systems: ["Calendar"],
        dataSources: ["Schedule"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Annual only = missed opportunities", "Reactive not proactive"],
        connectedTo: ["CS-06"],
      },
      {
        stepNumber: 6,
        stepId: "CS-06",
        stepName: "Spreadsheet Opportunity Tracking",
        description: "Rep tracks opportunities in personal spreadsheet",
        actor: { type: "human", name: "Service Representative", role: "Client Services" },
        duration: { value: 15, unit: "minutes", variability: "per batch" },
        systems: ["Excel"],
        dataSources: ["Personal notes"],
        isBottleneck: false,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["No centralized tracking", "Lost opportunities", "No visibility"],
        connectedTo: ["CS-07"],
      },
      {
        stepNumber: 7,
        stepId: "CS-07",
        stepName: "No Systematic Follow-Up",
        description: "Follow-up depends entirely on rep initiative",
        actor: { type: "human", name: "Service Representative", role: "Client Services" },
        duration: { value: 0, unit: "minutes", variability: "per item" },
        systems: ["None"],
        dataSources: ["Memory"],
        isBottleneck: true,
        isFrictionPoint: true,
        isDecisionPoint: false,
        painPoints: ["Inconsistent follow-up", "Lost opportunities", "No accountability"],
        connectedTo: [],
      },
    ],
    targetStateWorkflow: [
      {
        stepNumber: 1,
        stepId: "TS-01",
        stepName: "Life Event Detection",
        description: "AI monitors 15+ data sources to detect life events triggering product needs",
        actor: { type: "ai_agent", name: "Event Detection Agent", role: "Signal Processing" },
        duration: { value: 0, unit: "seconds", variability: "fixed" },
        systems: ["AI Platform", "Data Feeds"],
        dataSources: ["Public records", "Social signals", "Transaction patterns"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-02"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Event Detection", "Pattern Recognition"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 2,
        stepId: "TS-02",
        stepName: "AI Product Needs Prediction",
        description: "AI predicts which products client likely needs based on profile and events",
        actor: { type: "ai_agent", name: "Prediction Agent", role: "Recommendation" },
        duration: { value: 2, unit: "seconds", variability: "per item" },
        systems: ["ML Platform"],
        dataSources: ["Client profile", "Product catalog", "Similar clients"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-03"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Prediction", "Recommendation", "Propensity Modeling"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 3,
        stepId: "TS-03",
        stepName: "Propensity-to-Buy Scoring",
        description: "AI scores client's likelihood to purchase each recommended product",
        actor: { type: "ai_agent", name: "Scoring Agent", role: "Prioritization" },
        duration: { value: 1, unit: "seconds", variability: "per item" },
        systems: ["ML Platform"],
        dataSources: ["Historical conversion", "Behavioral signals"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-04"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Scoring", "Ranking"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 4,
        stepId: "TS-04",
        stepName: "Personalized Offer Package",
        description: "AI generates personalized product recommendations with tailored messaging",
        actor: { type: "ai_agent", name: "Offer Agent", role: "Content Generation" },
        duration: { value: 5, unit: "seconds", variability: "per item" },
        systems: ["AI Platform", "Content Library"],
        dataSources: ["Client preferences", "Communication history"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-05"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Generation", "Personalization"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 5,
        stepId: "TS-05",
        stepName: "Rep Reviews Recommendations",
        description: "Rep reviews AI recommendations and adds personal insights",
        actor: { type: "human", name: "Service Representative", role: "Client Services" },
        duration: { value: 3, unit: "minutes", variability: "per item" },
        systems: ["Recommendation Dashboard"],
        dataSources: ["AI recommendations", "Client history"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-06"],
        isAIEnabled: false,
        isHumanInTheLoop: true,
        aiCapabilities: [],
        model: null,
        automationLevel: "supervised",
      },
      {
        stepNumber: 6,
        stepId: "TS-06",
        stepName: "Automated Nurture Campaign",
        description: "AI launches personalized nurture campaign across optimal channels",
        actor: { type: "ai_agent", name: "Campaign Agent", role: "Marketing Automation" },
        duration: { value: 0, unit: "seconds", variability: "fixed" },
        systems: ["Marketing Automation", "Email", "SMS"],
        dataSources: ["Channel preferences", "Engagement history"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: ["TS-07"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Campaign Orchestration", "Channel Optimization"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 7,
        stepId: "TS-07",
        stepName: "Optimal Contact Timing",
        description: "AI determines best time and channel for rep follow-up",
        actor: { type: "ai_agent", name: "Timing Agent", role: "Engagement Optimization" },
        duration: { value: 1, unit: "seconds", variability: "per item" },
        systems: ["AI Platform"],
        dataSources: ["Response patterns", "Calendar data"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: true,
        painPoints: [],
        connectedTo: ["TS-08"],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Timing Optimization", "Channel Selection"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
      {
        stepNumber: 8,
        stepId: "TS-08",
        stepName: "Outcome Tracking & Model Refinement",
        description: "AI tracks outcomes and refines recommendations based on results",
        actor: { type: "system", name: "Learning Pipeline", role: "Continuous Improvement" },
        duration: { value: 0, unit: "seconds", variability: "fixed" },
        systems: ["ML Platform"],
        dataSources: ["Conversion data", "Client feedback"],
        isBottleneck: false,
        isFrictionPoint: false,
        isDecisionPoint: false,
        painPoints: [],
        connectedTo: [],
        isAIEnabled: true,
        isHumanInTheLoop: false,
        aiCapabilities: ["Learning", "Model Optimization"],
        model: "Claude Sonnet",
        automationLevel: "full",
      },
    ],
    comparisonMetrics: {
      timeReduction: { before: "33 min/opportunity", after: "8 min/opportunity", improvement: "76%" },
      costReduction: { before: "$85/opportunity", after: "$22/opportunity", improvement: "74%" },
      qualityImprovement: { before: "1.4 products/household", after: "2.3 products/household", improvement: "64%" },
      throughputIncrease: { before: "12 opportunities/week", after: "45 opportunities/week", improvement: "275%" },
    },
    implementationNotes: [
      "Integrate life event detection with CRM for real-time alerts",
      "Start with high-value client segment for maximum ROI",
      "A/B test AI recommendations against rep intuition",
    ],
    humanCheckpoints: [
      "Step TS-05: Rep reviews all AI recommendations before client outreach",
      "High-value clients (>$500K AUM) require personalized outreach",
    ],
  },
];

export function findMatchingTemplate(useCase: { name: string; description?: string; businessFunction?: string; frictionPoint?: string }): UseCaseWorkflowTemplate | null {
  const text = `${useCase.name} ${useCase.description || ""} ${useCase.frictionPoint || ""} ${useCase.businessFunction || ""}`.toLowerCase();
  
  let bestMatch: UseCaseWorkflowTemplate | null = null;
  let bestScore = 0;
  
  for (const template of USE_CASE_TEMPLATES) {
    let score = 0;
    for (const keyword of template.keywords) {
      if (text.includes(keyword.toLowerCase())) {
        score += 1;
      }
    }
    
    if (template.businessFunction && useCase.businessFunction) {
      if (useCase.businessFunction.toLowerCase().includes(template.businessFunction.toLowerCase()) ||
          template.businessFunction.toLowerCase().includes(useCase.businessFunction.toLowerCase())) {
        score += 2;
      }
    }
    
    if (score > bestScore) {
      bestScore = score;
      bestMatch = template;
    }
  }
  
  return bestScore >= 2 ? bestMatch : null;
}
